name : Web Automation Workflow

on :
  push :
    branches : ["main"]
  pull_reques :
    branches : ["main"]
  workflow_dispatch :

jobs :
  selenium-test :
    runs-on : ubuntu-latest

    steps :
    # download repo
      - uses : actions/checkout@v3

    # setup java
      - name : Set up jdk 11
        uses : actions/setups-java@v3
        with :
          java-version: '11'
          distribution: 'temurin'

      # setup graldew
      - name: Setup gradlew
        run: chmod +x gradlew

      # Execute gradle command for running cucumber test
      - name: Execute Test
        run: ./gradlew cucumber

      # Archive Test Result
      - name: Archive Test Result
        uses: actions/upload-artifact@v3.1.0
        if: always()
        with:
          name: Cucumber Report
          path: reports

      # Deploy to Github Pages
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_DIR: reports
